var BEREK = {
  user: {
    name: "Ania Kowalska",
    city: "Warszawa",
    initials: "AK",
    since: "2026",
    rating: 4.9
  },
  items: [
    {
      id: "B84721",
      cat: "Winyl",
      artist: "Pink Floyd",
      title: "The Dark Side of the Moon",
      edition: "UK first pressing, gatefold",
      country: "Wielka Brytania",
      year: 1973,
      label: "Harvest",
      catalog: "SHVL 804",
      matrix: "SHVL 804 A-2 / SHVL 804 B-2",
      condition: "VG+",
      value: 850,
      confidence: 96,
      status: "Na sprzedaż",
      loc: { place: "Magazyn", shelf: "Regał A", box: "Pudło 7" },
      wantedBy: 3,
      img: "assets/cover-spectrum.jpg",
      note: "Solidne pierwsze tłoczenie Harvest. Okładka z lekkimi otarciami narożników."
    },
    {
      id: "B84722",
      cat: "Winyl",
      artist: "Krzysztof Komeda",
      title: "Astigmatic",
      edition: "Polskie Nagrania Muza",
      country: "Polska",
      year: 1966,
      label: "Muza",
      catalog: "XL 0276",
      matrix: "XL 0276 A",
      condition: "VG",
      value: 620,
      confidence: 91,
      status: "Kolekcja prywatna",
      loc: { place: "Dom", shelf: "Pokój / Regał 2 / Półka 3", box: null },
      wantedBy: 5,
      img: "assets/cover-night.jpg",
      note: "Klasyk polskiego jazzu. Etykieta czytelna, szum tła akceptowalny."
    },
    {
      id: "B84723",
      cat: "Winyl",
      artist: "Czesław Niemen",
      title: "Enigmatic",
      edition: "Czerwona etykieta Muza",
      country: "Polska",
      year: 1970,
      label: "Polskie Nagrania Muza",
      catalog: "SXL 0576",
      matrix: "SXL 0576 A-3",
      condition: "NM",
      value: 340,
      confidence: 94,
      status: "Na sprzedaż",
      loc: { place: "Dom", shelf: "Regał 1 / Półka 2", box: null },
      wantedBy: 1,
      img: "assets/cover-horse.jpg",
      note: "Płyta praktycznie nieodtwarzana. Okładka w folii ochronnej."
    },
    {
      id: "B84724",
      cat: "Książka",
      artist: "Bolesław Prus",
      title: "Lalka",
      edition: "Wydanie z 1956",
      country: "Polska",
      year: 1956,
      label: "PIW",
      catalog: "ISBN brak (przed ISBN)",
      matrix: "—",
      condition: "Dobry",
      value: 180,
      confidence: 88,
      status: "Oddam",
      loc: { place: "Dom", shelf: "Pokój / Regał książek", box: null },
      wantedBy: 2,
      img: "assets/books-shelf.jpg",
      isbn: "—",
      lang: "polski",
      note: "Oprawa twarda, pieczątka biblioteczna na stronie tytułowej."
    },
    {
      id: "B84725",
      cat: "Książka",
      artist: "Stanisław Lem",
      title: "Solaris",
      edition: "Wyd. II",
      country: "Polska",
      year: 1968,
      label: "Wydawnictwo MON",
      catalog: "ISBN n/d",
      matrix: "—",
      condition: "VG",
      value: 220,
      confidence: 90,
      status: "Kolekcja prywatna",
      loc: { place: "Dom", shelf: "Półka L", box: null },
      wantedBy: 0,
      img: "assets/inherited.jpg",
      isbn: "—",
      lang: "polski",
      note: "Egzemplarz z dedykacją poprzedniego właściciela."
    },
    {
      id: "B84726",
      cat: "CD",
      artist: "Talk Talk",
      title: "Spirit of Eden",
      edition: "West German PDO",
      country: "Niemcy",
      year: 1988,
      label: "Parlophone",
      catalog: "CDP 7 46777 2",
      matrix: "PDO GERMANY",
      condition: "NM",
      value: 90,
      confidence: 93,
      status: "Na sprzedaż",
      loc: { place: "Dom", shelf: "Pudło CD-2", box: "Pudło CD-2" },
      wantedBy: 0,
      img: "assets/cover-bauhaus.jpg",
      note: "Wczesne tłoczenie PDO. Booklet kompletny."
    },
    {
      id: "B84727",
      cat: "Winyl",
      artist: "Miles Davis",
      title: "Kind of Blue",
      edition: "Columbia 6-eye",
      country: "USA",
      year: 1959,
      label: "Columbia",
      catalog: "CS 8163",
      matrix: "XSM 47326",
      condition: "G+",
      value: 410,
      confidence: 84,
      status: "Kolekcja prywatna",
      loc: { place: "Magazyn", shelf: "Regał B", box: "Pudło 2" },
      wantedBy: 4,
      img: "assets/vinyl-label.jpg",
      note: "Gra z szumem. Etykieta 6-eye, nie pierwsze stampery."
    },
    {
      id: "B84728",
      cat: "Winyl",
      artist: "Marek Grechuta",
      title: "Korowód",
      edition: "Muza",
      country: "Polska",
      year: 1971,
      label: "Polskie Nagrania",
      catalog: "SXL 0719",
      matrix: "SXL 0719 A",
      condition: "VG+",
      value: 160,
      confidence: 89,
      status: "Recykling",
      loc: { place: "Samochód", shelf: "—", box: "Teczka targowa" },
      wantedBy: 0,
      img: "assets/hero-vinyls.jpg",
      note: "Okładka mocno zniszczona — kandydat do recyklingu tektury / archiwizacji cyfrowej."
    }
  ],
  wants: [
    {
      id: "W1",
      query: "Pink Floyd — The Dark Side of the Moon, UK Harvest SHVL 804, A-2/B-2",
      max: 900,
      condition: "VG lub lepiej",
      country: "Wielka Brytania",
      edition: "UK first pressing",
      priority: "Wysoki",
      by: "Anna Nowak",
      city: "Kraków"
    },
    {
      id: "W2",
      query: "Lalka — Bolesław Prus, wydanie z 1956 roku",
      max: 200,
      condition: "jakikolwiek czytelny",
      country: "Polska",
      edition: "1956",
      priority: "Średni",
      by: "Piotr W.",
      city: "Łódź"
    }
  ],
  myWants: [
    {
      id: "MW1",
      query: "Budka Suflera — Cień wielkiej góry, pierwsze tłoczenie",
      max: 250,
      condition: "VG+",
      country: "Polska",
      edition: "1975 Muza",
      priority: "Średni"
    },
    {
      id: "MW2",
      query: "James Baldwin — Another Country, first US hardcover",
      max: 400,
      condition: "Good+",
      country: "USA",
      edition: "1962",
      priority: "Niski"
    }
  ],
  matches: [
    {
      id: "M1",
      seeker: "Anna Nowak",
      city: "Kraków",
      seeks: "Pink Floyd — The Dark Side of the Moon, UK Harvest SHVL 804",
      itemId: "B84721",
      score: 98
    }
  ],
  experts: [
    { id: "E1", name: "Tomasz Ryba", role: "Katalogowanie winylu", city: "Warszawa", rate: "120 zł/h" },
    { id: "E2", name: "Maja Lipska", role: "Wycena i sortowanie kolekcji", city: "Kraków", rate: "od 350 zł" },
    { id: "E3", name: "Studio Półka", role: "Fotografowanie i przygotowanie ofert", city: "Warszawa", rate: "pakiet 199 zł" },
    { id: "E4", name: "Clean Groove", role: "Czyszczenie płyt i okładek", city: "Poznań", rate: "8 zł / szt." },
    { id: "E5", name: "Berek Ride", role: "Transport kolekcji", city: "cała PL", rate: "wycena indywidualna" }
  ],
  orgs: [
    { id: "O1", name: "Fundacja Aleje Życia", type: "Fundacja", city: "Warszawa", blurb: "Kultura, pamięć i wsparcie seniorów." },
    { id: "O2", name: "Biblioteka na Woli", type: "Biblioteka", city: "Warszawa", blurb: "Przyjmuje książki w dobrym stanie." },
    { id: "O3", name: "SP nr 14", type: "Szkoła", city: "Warszawa", blurb: "Czytelnie i pracownie muzyczne." },
    { id: "O4", name: "Dom Kultury Włochy", type: "Dom kultury", city: "Warszawa", blurb: "Winyle na spotkania słuchackie." }
  ],
  recycle: [
    { kind: "Winyl (PVC)", how: "Nie wrzucaj do zmieszanych. Płyta to PVC — punkt zbiórki twardego plastiku lub partner recyklingu winylu.", partner: "Vinyl Cycle Warszawa", pickup: true },
    { kind: "Okładka / tektura", how: "Czysta tektura — makulatura. Folie ochronne — plastikowa frakcja.", partner: "MPSO Warszawa", pickup: false },
    { kind: "CD / DVD", how: "Poliwęglan. Punkty elektrośmieci lub partnerzy optyczni.", partner: "Elektro-odbiór Mokotów", pickup: true },
    { kind: "Książka zniszczona", how: "Jeżeli nie nadaje się do oddania — makulatura. Usuń twarde okładki z tworzywa.", partner: "Punkt makulatury Wola", pickup: false }
  ]
};
